security:
  oauth2:
    resource:
      userInfoUri: http://192.168.1.21:8901/auth/user

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    cc.coopersoft: DEBUG



#spring:
#  cloud:
#    stream:
#      bindings:
#        certificateExecute:
#          destination: certificateChangeTopic
#          content-type: application/json
#      kafka:
#        binder:
#          brokers: 192.168.1.21

signing:
  key: "345345fsdfsf5345"


spring:
  datasource:
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    url: "jdbc:mysql://127.0.0.1:3306/MONEY_ACCOUNT?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false"
    username: "root"
    password: "5257mq99"
    initialization-mode: always
  jpa:
    show-sql: "true"
    properties:
      hibernate:
        ddl-auto: "none"


